import { Router } from 'express';
import { prisma } from '../lib/prisma';
import * as fs from 'fs';
import * as path from 'path';

const router = Router();

// Path to forecast data JSON (generated by Python scheduler)
const FORECAST_PATH = process.env.FORECAST_DATA_PATH || 'E:/enviralog/weather_forecaster/forecast_data.json';

interface ForecastRow {
  step: number;
  predictedTime: string;
  temperature: number;
  humidity: number;
  airQuality: number;
  flame?: boolean;
}

interface ForecastData {
  lastUpdated: string;
  avgGapSeconds: number;
  lastReading: {
    timestamp: string;
    temperature: number;
    humidity: number;
    airQuality: number;
    flame?: boolean;
  };
  forecast: ForecastRow[];
  rowCount: number;
  mae: { temperature: number; humidity: number; airQuality: number };
}

// ── GET /api/forecast/status ───────────────────────────────────────────────
router.get('/status', async (_req, res) => {
  try {
    const forecastExists = fs.existsSync(FORECAST_PATH);
    let forecastData: ForecastData | null = null;
    
    if (forecastExists) {
      const raw = fs.readFileSync(FORECAST_PATH, 'utf-8');
      forecastData = JSON.parse(raw);
    }

    res.json({
      success: true,
      data: {
        modelLoaded: forecastExists,
        lastUpdated: forecastData?.lastUpdated || null,
        rowCount: forecastData?.rowCount || 0,
        durations: ['24hr'],
      }
    });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Failed to check forecast status' });
  }
});

// ── GET /api/forecast ──────────────────────────────────────────────────────
router.get('/', async (req, res) => {
  try {
    // Check if forecast data exists
    if (!fs.existsSync(FORECAST_PATH)) {
      return res.status(400).json({
        success: false,
        error: 'Forecast data not available. Wait for scheduler to train and generate forecast.'
      });
    }

    const raw = fs.readFileSync(FORECAST_PATH, 'utf-8');
    const data: ForecastData = JSON.parse(raw);

    const forecast = data.forecast;

    res.json({
      success: true,
      data: {
        duration: '24hr',
        minutes: 1440,
        steps: forecast.length,
        lastUpdated: data.lastUpdated,
        lastReading: data.lastReading,
        mae: data.mae,
        forecast,
      }
    });

  } catch (err: any) {
    console.error('Forecast error:', err);
    res.status(500).json({
      success: false,
      error: err.message || 'Failed to get forecast'
    });
  }
});

export default router;
